In [1]:
import numpy as np
nparray=np.array([[1,2,3],[2,3,4],[4,5,6]])
nparray

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [7]:
nparray.ndim

2

In [8]:
nparray.shape

(3, 3)

In [9]:
nparray.size

9

In [10]:
nparray.dtype

dtype('int32')

In [11]:
nparray.dtype.name

'int32'

In [12]:
np.array([1,2,3])

array([1, 2, 3])

In [14]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

In [16]:
A=np.array([1,2,3,4])
B=np.array([4,5,7,9])
A-B

array([-3, -3, -4, -5])

In [17]:
B**2

array([16, 25, 49, 81], dtype=int32)

In [18]:
np.cos(B)

array([-0.65364362,  0.28366219,  0.75390225, -0.91113026])

In [19]:
np.sin(B)

array([-0.7568025 , -0.95892427,  0.6569866 ,  0.41211849])

In [20]:
B<2

array([False, False, False, False])

In [21]:
B>4

array([False,  True,  True,  True])

In [22]:
A*B

array([ 4, 10, 21, 36])

In [23]:
np.dot(A,B)

71

In [24]:
nparray

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [25]:
nparray[0,2]

3

In [26]:
nparray[0,0:3]

array([1, 2, 3])

In [27]:
nparray[:,1]

array([2, 3, 5])

In [28]:
nparray

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [29]:
nparray.ravel()

array([1, 2, 3, 2, 3, 4, 4, 5, 6])

In [30]:
nparray=np.array([[1,2,3],[2,3,4],[4,5,6],[5,4,6]])

In [31]:
nparray

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6],
       [5, 4, 6]])

In [32]:
nparray.shape=(6,2)
nparray

array([[1, 2],
       [3, 2],
       [3, 4],
       [4, 5],
       [6, 5],
       [4, 6]])

In [33]:
nparray.transpose()

array([[1, 3, 3, 4, 6, 4],
       [2, 2, 4, 5, 5, 6]])